// Generated by AI because there are too many stuff to bind with mixed types and combinations
// so it is not worth the effort

#include "../Scripting_Internal.h"
#define GLM_ENABLE_EXPERIMENTAL
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <glm/gtx/norm.hpp>

using namespace glm;

namespace {

	template<typename V, typename S>
	void bind_indexing(sol::usertype<V>& ut, int size) {
		ut[sol::meta_function::index] = [size](const V& v, int i) -> S {
			if (i < 1 || i > size) throw std::out_of_range("index out of range");
			return glm::value_ptr(v)[i - 1];
			};

		ut[sol::meta_function::new_index] = [size](V& v, int i, S value) {
			if (i < 1 || i > size) throw std::out_of_range("index out of range");
			glm::value_ptr(v)[i - 1] = value;
			};
	}

	template<typename V, typename S>
	void bind_vec_ops(sol::usertype<V>& ut) {

		ut[sol::meta_function::addition] = sol::overload(
			[](const V& a, const V& b) { return a + b; },
			[](const V& a, S b) { return a + V(b); },
			[](S a, const V& b) { return V(a) + b; }
		);

		ut[sol::meta_function::subtraction] = sol::overload(
			[](const V& a, const V& b) { return a - b; },
			[](const V& a, S b) { return a - V(b); },
			[](S a, const V& b) { return V(a) - b; }
		);

		ut[sol::meta_function::multiplication] = sol::overload(
			[](const V& a, const V& b) { return a * b; },
			[](const V& a, S b) { return a * b; },
			[](S a, const V& b) { return a * b; }
		);

		ut[sol::meta_function::division] = sol::overload(
			[](const V& a, const V& b) { return a / b; },
			[](const V& a, S b) { return a / b; },
			[](S a, const V& b) { return V(a) / b; }
		);
	}

	template<typename V>
	void bind_vec_float_funcs(sol::usertype<V>& ut) {
		ut.set_function("length", [](const V& v) {
			return glm::length(v);
			});

		ut.set_function("normalize", [](const V& v) {
			return glm::normalize(v);
			});

		ut.set_function("dot", [](const V& a, const V& b) {
			return glm::dot(a, b);
			});
	}

	template<typename V>
	void bind_cross(sol::usertype<V>& ut) {
		ut.set_function("cross", [](const V& a, const V& b) {
			return glm::cross(a, b);
			});
	}

	template<typename M>
	void bind_matrix_common(sol::usertype<M>& ut) {

		ut.set_function("transpose", [](const M& m) {
			return glm::transpose(m);
			});

		ut.set_function("inverse", [](const M& m) {
			return glm::inverse(m);
			});

		ut.set_function("determinant", [](const M& m) {
			return glm::determinant(m);
			});
	}

}

namespace Yngin {

	void ScriptsManager::Impl::bindGlmTypes() {

		// ================= Vec2 =================
		{
			auto ut = lua.new_usertype<vec2>("Vec2",
				sol::constructors<
				vec2(),
				vec2(float),
				vec2(float, float)
				>(),
				"x", &vec2::x,
				"y", &vec2::y
			);

			bind_vec_ops<vec2, float>(ut);
			bind_vec_float_funcs<vec2>(ut);
			bind_indexing<vec2, float>(ut, 2);
		}

		// ================= Vec3 =================
		{
			auto ut = lua.new_usertype<vec3>("Vec3",
				sol::constructors<
				vec3(),
				vec3(float),
				vec3(float, float, float),
				vec3(vec2, float),
				vec3(float, vec2)
				>(),
				"x", &vec3::x,
				"y", &vec3::y,
				"z", &vec3::z
			);

			bind_vec_ops<vec3, float>(ut);
			bind_vec_float_funcs<vec3>(ut);
			bind_cross<vec3>(ut);
			bind_indexing<vec3, float>(ut, 3);
		}

		// ================= Vec4 =================
		{
			auto ut = lua.new_usertype<vec4>("Vec4",
				sol::constructors<
				vec4(),
				vec4(float),
				vec4(float, float, float, float),
				vec4(vec3, float),
				vec4(float, vec3),
				vec4(vec2, vec2)
				>(),
				"x", &vec4::x,
				"y", &vec4::y,
				"z", &vec4::z,
				"w", &vec4::w
			);

			bind_vec_ops<vec4, float>(ut);
			bind_vec_float_funcs<vec4>(ut);
			bind_indexing<vec4, float>(ut, 4);
		}

		// ================= IVec2 =================
		{
			auto ut = lua.new_usertype<ivec2>("IVec2",
				sol::constructors<
				ivec2(),
				ivec2(int),
				ivec2(int, int)
				>(),
				"x", &ivec2::x,
				"y", &ivec2::y
			);

			bind_vec_ops<ivec2, int>(ut);
			bind_indexing<ivec2, int>(ut, 2);
		}

		// ================= IVec3 =================
		{
			auto ut = lua.new_usertype<ivec3>("IVec3",
				sol::constructors<
				ivec3(),
				ivec3(int),
				ivec3(int, int, int),
				ivec3(ivec2, int),
				ivec3(int, ivec2)
				>(),
				"x", &ivec3::x,
				"y", &ivec3::y,
				"z", &ivec3::z
			);

			bind_vec_ops<ivec3, int>(ut);
			bind_indexing<ivec3, int>(ut, 3);
		}

		// ================= IVec4 =================
		{
			auto ut = lua.new_usertype<ivec4>("IVec4",
				sol::constructors<
				ivec4(),
				ivec4(int),
				ivec4(int, int, int, int),
				ivec4(ivec3, int),
				ivec4(int, ivec3),
				ivec4(ivec2, ivec2)
				>(),
				"x", &ivec4::x,
				"y", &ivec4::y,
				"z", &ivec4::z,
				"w", &ivec4::w
			);

			bind_vec_ops<ivec4, int>(ut);
			bind_indexing<ivec4, int>(ut, 4);
		}

		// ================= Mat3 =================
		{
			auto ut = lua.new_usertype<mat3>("Mat3",
				sol::constructors<
				mat3(),
				mat3(float)
				>()
			);

			ut[sol::meta_function::multiplication] = sol::overload(
				[](const mat3& a, const mat3& b) { return a * b; },
				[](const mat3& m, const vec3& v) { return m * v; }
			);

			bind_matrix_common<mat3>(ut);
		}

		// ================= Mat4 =================
		{
			auto ut = lua.new_usertype<mat4>("Mat4",
				sol::constructors<
				mat4(),
				mat4(float)
				>()
			);

			ut[sol::meta_function::multiplication] = sol::overload(
				[](const mat4& a, const mat4& b) { return a * b; },
				[](const mat4& m, const vec4& v) { return m * v; }
			);

			bind_matrix_common<mat4>(ut);

			ut.set_function("translate", [](const mat4& m, const vec3& v) {
				return glm::translate(m, v);
				});

			ut.set_function("scale", [](const mat4& m, const vec3& v) {
				return glm::scale(m, v);
				});

			ut.set_function("rotate", [](const mat4& m, float angle, const vec3& axis) {
				return glm::rotate(m, angle, axis);
				});
		}
	}

}